### ISSUE TITLE
Our README file is completely empty - we should definitely fix that

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mozwebqa-examples#2]
https://github.com/mozilla/mozwebqa-examples/blob/master/README.md is empty right now - we really should address that with some content :-)

**Comment by terrameijar** [comment]
I'd like to work on this, any help doing so would be appreciated

**Comment by terrameijar** [comment]
Here's something to get us started https://github.com/mozilla/mozwebqa-examples/pull/3

**Comment by stephendonner** [comment]
Oh, FIX IT WE WILL </maniacalLaughter>...with a "this repo is no longer actively maintained" notice - so there :-)
