### ISSUE TITLE
Migrate examples to PyPOM

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/mozwebqa-examples#5]
PyPOM is our new page object model package that is currently in development. This project should be the first to be converted to use it, and that conversion will be done also in order to validate that PyPOM works and has everything we need thus far.

**Comment by davehunt** [comment]
This was done in https://github.com/mozilla/mozwebqa-examples/commit/3f698d16b0939df2b09bac49b27d8b24eebb0ed2
