### ISSUE TITLE
Switch to Tox

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mozwebqa-examples#7]
bidpom, fxapom, mozillians-tests have already switched (with addon-tests on the way), and this is now being tracked in our Baseline: https://wiki.mozilla.org/TestEngineering/Web/Automation/Baseline

Let's switch over to Tox: https://tox.readthedocs.io/en/latest/

**Comment by davehunt** [comment]
Are you still intending on working on this @stephendonner?

**Comment by stephendonner** [comment]
@davehunt yep; WIP patch up for r?/feedback in https://github.com/mozilla/mozwebqa-examples/pull/9

**Comment by stephendonner** [comment]
/me hits reverse, and then the brakes.  NOPE.
