### ISSUE TITLE
Enable pyup.io for taking care of dependencies

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozwebqa-examples#8]
We want to enable [pyup.io](https://pyup.io/) for our projects to take care of automating the updates to our dependencies. Here's what's needed:

- [ ] Add repository to pyup.io (@davehunt can take care of this once the above is merged).
- [ ] Add pyup.io badges for updates and python 3 readyness. See https://github.com/mozilla/PyPOM/commit/931c41b964f1c9950983c078d0583ef708ac8af9 for an example of this.
- [ ] Remove requires.io badge from README.
- [ ] Remove repository from [requires.io](https://requires.io/) (@davehunt can take care of this once pyup.io is working)

**Comment by stephendonner** [comment]
NOPE
